/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export interface AdminAccess {
    authenticated: boolean;
    authorized: boolean;
    /** @nullable */
    email: string | null;
}
//# sourceMappingURL=adminAccess.d.ts.map