/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export interface AdminParticipantEmail {
  ownerId: string;
  ownerName: string;
  /** @nullable */
  email: string | null;
  isAdmin: boolean;
}
