/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { AvailablePlayerPosition } from './availablePlayerPosition';
import type { AvailablePlayerScoringStatus } from './availablePlayerScoringStatus';
export interface AvailablePlayer {
    nhlPlayerId: number;
    name: string;
    /** @nullable */
    team: string | null;
    position: AvailablePlayerPosition;
    /** @nullable */
    goals: number | null;
    /** @nullable */
    assists: number | null;
    /** @nullable */
    powerPlayGoals: number | null;
    /** @nullable */
    shortHandedGoals: number | null;
    /** @nullable */
    overtimeGoals: number | null;
    /** @nullable */
    poolPoints: number | null;
    /** @nullable */
    gamesPlayed: number | null;
    /** @nullable */
    wins: number | null;
    /** @nullable */
    shutouts: number | null;
    scoringStatus: AvailablePlayerScoringStatus;
    /** @nullable */
    reason: string | null;
}
//# sourceMappingURL=availablePlayer.d.ts.map