/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type AvailablePlayerScoringStatus = typeof AvailablePlayerScoringStatus[keyof typeof AvailablePlayerScoringStatus];
export declare const AvailablePlayerScoringStatus: {
    readonly complete: "complete";
    readonly partial: "partial";
    readonly pending: "pending";
};
//# sourceMappingURL=availablePlayerScoringStatus.d.ts.map