/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type AvailablePlayersSnapshotStatus = typeof AvailablePlayersSnapshotStatus[keyof typeof AvailablePlayersSnapshotStatus];


export const AvailablePlayersSnapshotStatus = {
  available: 'available',
  partial: 'partial',
  stale: 'stale',
  unavailable: 'unavailable',
} as const;
