/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type AvailablePlayerScoringStatus = typeof AvailablePlayerScoringStatus[keyof typeof AvailablePlayerScoringStatus];


export const AvailablePlayerScoringStatus = {
  complete: 'complete',
  partial: 'partial',
  pending: 'pending',
} as const;
