/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type AvailablePlayerPosition = typeof AvailablePlayerPosition[keyof typeof AvailablePlayerPosition];
export declare const AvailablePlayerPosition: {
    readonly F: "F";
    readonly C: "C";
    readonly D: "D";
    readonly G: "G";
};
//# sourceMappingURL=availablePlayerPosition.d.ts.map