/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type AvailablePlayerPosition = typeof AvailablePlayerPosition[keyof typeof AvailablePlayerPosition];


export const AvailablePlayerPosition = {
  F: 'F',
  C: 'C',
  D: 'D',
  G: 'G',
} as const;
