/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type AvailablePlayersSnapshotCatalogTeamsTotal = typeof AvailablePlayersSnapshotCatalogTeamsTotal[keyof typeof AvailablePlayersSnapshotCatalogTeamsTotal];


export const AvailablePlayersSnapshotCatalogTeamsTotal = {
  NUMBER_32: 32,
} as const;
