/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type AvailablePlayersSnapshotStatus = typeof AvailablePlayersSnapshotStatus[keyof typeof AvailablePlayersSnapshotStatus];
export declare const AvailablePlayersSnapshotStatus: {
    readonly available: "available";
    readonly partial: "partial";
    readonly stale: "stale";
    readonly unavailable: "unavailable";
};
//# sourceMappingURL=availablePlayersSnapshotStatus.d.ts.map