/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type AvailablePlayersSnapshotCatalogTeamsTotal = typeof AvailablePlayersSnapshotCatalogTeamsTotal[keyof typeof AvailablePlayersSnapshotCatalogTeamsTotal];
export declare const AvailablePlayersSnapshotCatalogTeamsTotal: {
    readonly NUMBER_32: 32;
};
//# sourceMappingURL=availablePlayersSnapshotCatalogTeamsTotal.d.ts.map