/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type AvailablePlayersSnapshotSeason = typeof AvailablePlayersSnapshotSeason[keyof typeof AvailablePlayersSnapshotSeason];


export const AvailablePlayersSnapshotSeason = {
  NUMBER_20262027: 20262027,
} as const;
