/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PoolPoll } from './poolPoll';
export type ClaimPoolPollPopup200 = {
    poll: PoolPoll | null;
};
//# sourceMappingURL=claimPoolPollPopup200.d.ts.map