/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type DailyReportHealthStatus = typeof DailyReportHealthStatus[keyof typeof DailyReportHealthStatus];
export declare const DailyReportHealthStatus: {
    readonly scheduled: "scheduled";
    readonly pending: "pending";
    readonly delayed: "delayed";
    readonly published: "published";
};
//# sourceMappingURL=dailyReportHealthStatus.d.ts.map