/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type DailyReportResponseStatus = typeof DailyReportResponseStatus[keyof typeof DailyReportResponseStatus];
export declare const DailyReportResponseStatus: {
    readonly published: "published";
    readonly pending: "pending";
    readonly unavailable: "unavailable";
};
//# sourceMappingURL=dailyReportResponseStatus.d.ts.map