/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export interface DailyReportRace {
    participants: string[];
    gap: number;
}
//# sourceMappingURL=dailyReportRace.d.ts.map