/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export interface DailyReportSeasonLeader {
    playerId: string;
    playerName: string;
    ownerName: string;
    team: string;
    poolPoints: number;
}
//# sourceMappingURL=dailyReportSeasonLeader.d.ts.map