/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { ScoreReason } from './scoreReason';
export interface DailyScoringRow {
    ownerId: string;
    ownerName: string;
    playerId: string;
    playerName: string;
    team: string;
    goals: number;
    assists: number;
    powerPlayGoals: number;
    shortHandedGoals: number;
    overtimeGoals: number;
    hatTrick: boolean;
    poolPoints: number;
    scoringBreakdown: ScoreReason[];
}
//# sourceMappingURL=dailyScoringRow.d.ts.map