/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyReportHealthFailureCategory } from './dailyReportHealthFailureCategory';
import type { DailyReportHealthStatus } from './dailyReportHealthStatus';
export interface DailyReportHealth {
    reportDate: string;
    status: DailyReportHealthStatus;
    /** False when the database cannot confirm today's publication status */
    publicationVerified: boolean;
    graceMinutes: number;
    /**
       * Latest publication attempt observed by this server process
       * @nullable
       */
    lastAttemptAt: string | null;
    /**
       * Last confirmed successful publication, null if not yet known
       * @nullable
       */
    lastPublishedAt: string | null;
    /** @nullable */
    failureCategory: DailyReportHealthFailureCategory;
    /** Server observation start; attempt history resets on restart */
    observedSince: string;
}
//# sourceMappingURL=dailyReportHealth.d.ts.map