/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyAnalysisStatus } from './dailyAnalysisStatus';
import type { DailyScoringRow } from './dailyScoringRow';
import type { OwnerAnalysis } from './ownerAnalysis';
export interface DailyAnalysis {
    date: Date;
    status: DailyAnalysisStatus;
    summary: string;
    owners: OwnerAnalysis[];
    scoring: DailyScoringRow[];
}
//# sourceMappingURL=dailyAnalysis.d.ts.map