/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PoolPoll } from './poolPoll';
export interface DailyPoolPolls {
    today: string;
    yesterday: string;
    serverNow: string;
    rollsOverAt: string;
    polls: PoolPoll[];
}
//# sourceMappingURL=dailyPoolPolls.d.ts.map