/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
/**
 * @nullable
 */
export type DailyReportHealthFailureCategory = typeof DailyReportHealthFailureCategory[keyof typeof DailyReportHealthFailureCategory] | null;
export declare const DailyReportHealthFailureCategory: {
    readonly database_unavailable: "database_unavailable";
    readonly scoring_not_verified: "scoring_not_verified";
    readonly report_generation_failed: "report_generation_failed";
    readonly publication_failed: "publication_failed";
    readonly unknown: "unknown";
};
//# sourceMappingURL=dailyReportHealthFailureCategory.d.ts.map