/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { OwnerAnalysis } from './ownerAnalysis';
export type DailyReportOwner = OwnerAnalysis & ({
    gapFromFirst: number;
    /** @nullable */
    movement: number | null;
    tied: boolean;
    /** @nullable */
    activePlayers: number | null;
});
//# sourceMappingURL=dailyReportOwner.d.ts.map