/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type DailyAnalysisStatus = typeof DailyAnalysisStatus[keyof typeof DailyAnalysisStatus];
export declare const DailyAnalysisStatus: {
    readonly final: "final";
    readonly pending: "pending";
    readonly unavailable: "unavailable";
};
//# sourceMappingURL=dailyAnalysisStatus.d.ts.map