/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type DashboardSeasonPhase = typeof DashboardSeasonPhase[keyof typeof DashboardSeasonPhase];


export const DashboardSeasonPhase = {
  preseason: 'preseason',
  regularSeason: 'regularSeason',
  offseason: 'offseason',
  unavailable: 'unavailable',
} as const;
