/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type DashboardSeasonPhase = typeof DashboardSeasonPhase[keyof typeof DashboardSeasonPhase];
export declare const DashboardSeasonPhase: {
    readonly preseason: "preseason";
    readonly regularSeason: "regularSeason";
    readonly offseason: "offseason";
    readonly unavailable: "unavailable";
};
//# sourceMappingURL=dashboardSeasonPhase.d.ts.map