/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardSeasonPhase } from './dashboardSeasonPhase';
import type { GameSummary } from './gameSummary';
import type { OwnerStanding } from './ownerStanding';
import type { PlayerSummary } from './playerSummary';
import type { Transaction } from './transaction';

export interface Dashboard {
  poolTitle: string;
  seasonLabel: string;
  seasonPhase: DashboardSeasonPhase;
  /** @nullable */
  dataUpdatedAt: Date | null;
  live: boolean;
  standings: OwnerStanding[];
  games: GameSummary[];
  yesterdayLeaders: OwnerStanding[];
  injuries: PlayerSummary[];
  recentTransactions: Transaction[];
  unresolvedSelections: number;
}
