/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type DraftRosterSelectionPosition = typeof DraftRosterSelectionPosition[keyof typeof DraftRosterSelectionPosition];


export const DraftRosterSelectionPosition = {
  F: 'F',
  D: 'D',
  G: 'G',
} as const;
