/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type DraftRosterSelectionIdentityCandidatesItemPosition = typeof DraftRosterSelectionIdentityCandidatesItemPosition[keyof typeof DraftRosterSelectionIdentityCandidatesItemPosition];
export declare const DraftRosterSelectionIdentityCandidatesItemPosition: {
    readonly F: "F";
    readonly D: "D";
};
//# sourceMappingURL=draftRosterSelectionIdentityCandidatesItemPosition.d.ts.map