/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type DraftRosterSelectionAssetType = typeof DraftRosterSelectionAssetType[keyof typeof DraftRosterSelectionAssetType];


export const DraftRosterSelectionAssetType = {
  skater: 'skater',
  goalieTeam: 'goalieTeam',
} as const;
