/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type DraftRosterSelectionIdentityCandidatesItemPosition = typeof DraftRosterSelectionIdentityCandidatesItemPosition[keyof typeof DraftRosterSelectionIdentityCandidatesItemPosition];


export const DraftRosterSelectionIdentityCandidatesItemPosition = {
  F: 'F',
  D: 'D',
} as const;
