/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type DraftRosterSelectionPosition = typeof DraftRosterSelectionPosition[keyof typeof DraftRosterSelectionPosition];
export declare const DraftRosterSelectionPosition: {
    readonly F: "F";
    readonly D: "D";
    readonly G: "G";
};
//# sourceMappingURL=draftRosterSelectionPosition.d.ts.map