/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { DraftRosterSelectionAssetType } from './draftRosterSelectionAssetType';
import type { DraftRosterSelectionIdentityCandidatesItem } from './draftRosterSelectionIdentityCandidatesItem';
import type { DraftRosterSelectionPosition } from './draftRosterSelectionPosition';
import type { PhotoConfirmedGoalie } from './photoConfirmedGoalie';
export interface DraftRosterSelection {
    round: number;
    originalText: string;
    assetType: DraftRosterSelectionAssetType;
    position: DraftRosterSelectionPosition;
    /** @nullable */
    reviewNote: string | null;
    /** @nullable */
    confirmedName?: string | null;
    /** @nullable */
    confirmedTeam?: string | null;
    /** @nullable */
    confirmedLastName?: string | null;
    /** @nullable */
    nhlPlayerId?: number | null;
    /** @nullable */
    identityCheckedAt?: Date | null;
    /** @nullable */
    identitySource?: string | null;
    /**
       * Actual pickup instant; this player earns participant points only after pickup.
       * @nullable
       */
    acquiredAt?: Date | null;
    /**
       * Actual drop instant; historical points remain frozen and the player is no longer owned.
       * @nullable
       */
    droppedAt?: Date | null;
    /** Individual goalies confirmed from uploaded photos or the approved official NHL roster snapshot for this original draft slot. Club entries are provenance only and do not score. */
    goalies?: PhotoConfirmedGoalie[];
    /** True when this goalie slot has no confirmed individual names. Missing goalie points are unknown, not zero. */
    goalieNamesPending?: boolean;
    identityCandidates?: DraftRosterSelectionIdentityCandidatesItem[];
}
//# sourceMappingURL=draftRosterSelection.d.ts.map