/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PlayerStats } from './playerStats';
import type { ScoreReason } from './scoreReason';
export type GameLogEntry = PlayerStats & ({
    gameId: string;
    date: Date;
    opponent: string;
    /** @nullable */
    result?: string | null;
    scoringBreakdown: ScoreReason[];
});
//# sourceMappingURL=gameLogEntry.d.ts.map