/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export interface GameSummary {
    gameId: string;
    awayTeam: string;
    homeTeam: string;
    status: string;
    /** @nullable */
    startTime: Date | null;
    poolPlayers: string[];
}
//# sourceMappingURL=gameSummary.d.ts.map