/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { DraftRoster } from './draftRoster';
import type { GetAdminManagement200AccountsItem } from './getAdminManagement200AccountsItem';
import type { GetAdminManagement200AuditItem } from './getAdminManagement200AuditItem';
import type { Transaction } from './transaction';
export type GetAdminManagement200 = {
    accounts: GetAdminManagement200AccountsItem[];
    rosters: DraftRoster[];
    transactions: Transaction[];
    audit: GetAdminManagement200AuditItem[];
};
//# sourceMappingURL=getAdminManagement200.d.ts.map