/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type GetAuthConfig200 = {
    publishableKey: string;
};
//# sourceMappingURL=getAuthConfig200.d.ts.map