/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PoolPoll } from './poolPoll';
export type GetAdminPoolPolls200 = {
    polls: PoolPoll[];
};
//# sourceMappingURL=getAdminPoolPolls200.d.ts.map