/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { GetPlayersDirection } from './getPlayersDirection';
import type { GetPlayersPosition } from './getPlayersPosition';
import type { GetPlayersSort } from './getPlayersSort';
export type GetPlayersParams = {
    search?: string;
    team?: string;
    position?: GetPlayersPosition;
    available?: boolean;
    sort?: GetPlayersSort;
    direction?: GetPlayersDirection;
};
//# sourceMappingURL=getPlayersParams.d.ts.map