/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type GetPlayersPosition = typeof GetPlayersPosition[keyof typeof GetPlayersPosition];
export declare const GetPlayersPosition: {
    readonly F: "F";
    readonly D: "D";
    readonly G: "G";
};
//# sourceMappingURL=getPlayersPosition.d.ts.map