/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type GetPlayersDirection = typeof GetPlayersDirection[keyof typeof GetPlayersDirection];
export declare const GetPlayersDirection: {
    readonly asc: "asc";
    readonly desc: "desc";
};
//# sourceMappingURL=getPlayersDirection.d.ts.map