/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type GetPlayersDirection = typeof GetPlayersDirection[keyof typeof GetPlayersDirection];


export const GetPlayersDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;
