/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type GetPlayersSort = typeof GetPlayersSort[keyof typeof GetPlayersSort];
export declare const GetPlayersSort: {
    readonly name: "name";
    readonly team: "team";
    readonly position: "position";
    readonly gamesPlayed: "gamesPlayed";
    readonly poolPoints: "poolPoints";
    readonly goals: "goals";
    readonly assists: "assists";
    readonly lastGamePoints: "lastGamePoints";
};
//# sourceMappingURL=getPlayersSort.d.ts.map