/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
//# sourceMappingURL=healthStatus.d.ts.map