/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type ImportSelectionSource = typeof ImportSelectionSource[keyof typeof ImportSelectionSource];
export declare const ImportSelectionSource: {
    readonly confirmedRoster: "confirmedRoster";
    readonly draftBoard: "draftBoard";
};
//# sourceMappingURL=importSelectionSource.d.ts.map