/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { ImportSelectionConfidence } from './importSelectionConfidence';
import type { ImportSelectionSource } from './importSelectionSource';
export interface ImportSelection {
    id: string;
    ownerId: string;
    ownerName: string;
    /** @nullable */
    round: number | null;
    originalText: string;
    /** @nullable */
    matchedPlayerId: string | null;
    /** @nullable */
    matchedName: string | null;
    /** @nullable */
    position: string | null;
    /** @nullable */
    team: string | null;
    /** @nullable */
    nhlPlayerId: string | null;
    confidence: ImportSelectionConfidence;
    source: ImportSelectionSource;
}
//# sourceMappingURL=importSelection.d.ts.map