/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export interface ImportSelectionUpdate {
    matchedPlayerId: string;
    matchedName: string;
    position: string;
    team: string;
    nhlPlayerId: string;
    confirm: boolean;
}
//# sourceMappingURL=importSelectionUpdate.d.ts.map