/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type ImportSelectionConfidence = typeof ImportSelectionConfidence[keyof typeof ImportSelectionConfidence];
export declare const ImportSelectionConfidence: {
    readonly verified: "verified";
    readonly needsConfirmation: "needsConfirmation";
    readonly unresolved: "unresolved";
};
//# sourceMappingURL=importSelectionConfidence.d.ts.map