/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export interface NhlSourceGame {
  id: number;
  season: number;
  gameType: number;
  gameDate: Date;
  gameState: string;
  /** @nullable */
  startTimeUTC: Date | null;
  awayAbbrev: string;
  awayName: string;
  /** @nullable */
  awayScore: number | null;
  homeAbbrev: string;
  homeName: string;
  /** @nullable */
  homeScore: number | null;
  poolEligible: boolean;
}
