/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type NhlSourceSnapshotStatus = typeof NhlSourceSnapshotStatus[keyof typeof NhlSourceSnapshotStatus];


export const NhlSourceSnapshotStatus = {
  starting: 'starting',
  available: 'available',
  stale: 'stale',
  unavailable: 'unavailable',
} as const;
