/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyScoringRow } from './dailyScoringRow';

export interface OwnerAnalysis {
  ownerId: string;
  ownerName: string;
  dailyPoints: number;
  seasonPoints: number;
  rank: number;
  /** @nullable */
  previousRank: number | null;
  narrative: string;
  scoring: DailyScoringRow[];
}
