/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { OwnerStanding } from './ownerStanding';
import type { RosterAsset } from './rosterAsset';

export interface OwnerDetail {
  owner: OwnerStanding;
  skaters: RosterAsset[];
  goalieTeams: RosterAsset[];
}
