/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PlayerStats } from './playerStats';

export type PlayerSummary = PlayerStats & ({
  id: string;
  /** @nullable */
  nhlPlayerId: string | null;
  name: string;
  position: string;
  /** @nullable */
  team: string | null;
  /** @nullable */
  injuryStatus: string | null;
  /** @nullable */
  ownerId: string | null;
  /** @nullable */
  ownerName: string | null;
  active: boolean;
  /** @nullable */
  lastGameDate: Date | null;
});
