/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { GameLogEntry } from './gameLogEntry';
import type { PlayerSummary } from './playerSummary';
import type { Transaction } from './transaction';

export type PlayerProfile = PlayerSummary & ({
  /** @nullable */
  age: number | null;
  /** @nullable */
  headshotUrl: string | null;
  /** @nullable */
  currentOwnerId: string | null;
  /** @nullable */
  currentOwnerName: string | null;
  transactionHistory: Transaction[];
  gameLog: GameLogEntry[];
});
