/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PoolPollAnswers } from './poolPollAnswers';
import type { PoolPollParticipant } from './poolPollParticipant';
import type { PoolPollQuestionsItem } from './poolPollQuestionsItem';
import type { PoolPollStatus } from './poolPollStatus';

export interface PoolPoll {
  id: string;
  title: string;
  /** @nullable */
  publicationDate?: string | null;
  /** @nullable */
  publishedAt?: string | null;
  /** @nullable */
  closesAt?: string | null;
  status?: PoolPollStatus;
  isOpen?: boolean;
  popupViewed?: boolean;
  eligibleParticipantCount?: number;
  legacy?: boolean;
  respondentCount: number;
  participants: PoolPollParticipant[];
  structureLocked: boolean;
  canVote: boolean;
  hasVoted: boolean;
  myAnswers: PoolPollAnswers | null;
  questions: PoolPollQuestionsItem[];
}
