/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type PoolInjurySnapshotRefreshHour = typeof PoolInjurySnapshotRefreshHour[keyof typeof PoolInjurySnapshotRefreshHour];


export const PoolInjurySnapshotRefreshHour = {
  NUMBER_8: 8,
} as const;
