/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyScoringRow } from './dailyScoringRow';
export interface PoolStanding {
    id: string;
    name: string;
    /** @nullable */
    rank: number | null;
    /** @nullable */
    previousRank: number | null;
    /** @nullable */
    rankMovement: number | null;
    /** @nullable */
    seasonPoints: number | null;
    /** @nullable */
    yesterdayPoints: number | null;
    /** @nullable */
    livePoints: number | null;
    /** Verified ownership-adjusted scoring for the current pool day, supplied in the same snapshot as livePoints. Omitted when current-day evidence is unavailable or a historical date is selected. */
    todayScorers?: DailyScoringRow[];
    /** Verified ownership-adjusted scoring for the prior pool day, supplied in the same snapshot as yesterdayPoints. Omitted when prior-day evidence or its numeric total is unavailable. */
    yesterdayScorers?: DailyScoringRow[];
    /** @nullable */
    playing: number | null;
    /** @nullable */
    gamesPlayed: number | null;
    /** @nullable */
    pointsPerGame: number | null;
    /** @nullable */
    transactionsUsed: number | null;
    rosterComplete: boolean;
}
//# sourceMappingURL=poolStanding.d.ts.map