/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type PoolInjurySnapshotTimezone = typeof PoolInjurySnapshotTimezone[keyof typeof PoolInjurySnapshotTimezone];


export const PoolInjurySnapshotTimezone = {
  'America/Toronto': 'America/Toronto',
} as const;
