/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type PoolManagementInputAction = typeof PoolManagementInputAction[keyof typeof PoolManagementInputAction];


export const PoolManagementInputAction = {
  account: 'account',
  invitation: 'invitation',
  allowance: 'allowance',
  reverse: 'reverse',
  roster: 'roster',
  eligibility: 'eligibility',
} as const;
