/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PoolPlayerInjuryStatus } from './poolPlayerInjuryStatus';

export interface PoolPlayerInjury {
  nhlPlayerId: number;
  name: string;
  /** @nullable */
  team: string | null;
  status: PoolPlayerInjuryStatus;
  /** @nullable */
  details: string | null;
  /** @nullable */
  sourceUrl: string | null;
  /** @nullable */
  reportedAt: Date | null;
  /** @nullable */
  checkedAt: Date | null;
}
