/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type PoolScoringRowAssetType = typeof PoolScoringRowAssetType[keyof typeof PoolScoringRowAssetType];
export declare const PoolScoringRowAssetType: {
    readonly skater: "skater";
    readonly goalieTeam: "goalieTeam";
    readonly goalie: "goalie";
};
//# sourceMappingURL=poolScoringRowAssetType.d.ts.map