/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type PoolScoringSnapshotSeason = typeof PoolScoringSnapshotSeason[keyof typeof PoolScoringSnapshotSeason];
export declare const PoolScoringSnapshotSeason: {
    readonly NUMBER_20262027: 20262027;
};
//# sourceMappingURL=poolScoringSnapshotSeason.d.ts.map