/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type PoolScoringSnapshotStatus = typeof PoolScoringSnapshotStatus[keyof typeof PoolScoringSnapshotStatus];
export declare const PoolScoringSnapshotStatus: {
    readonly available: "available";
    readonly partial: "partial";
    readonly unavailable: "unavailable";
    readonly stale: "stale";
};
//# sourceMappingURL=poolScoringSnapshotStatus.d.ts.map