/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export interface PoolPollParticipant {
    name: string;
}
//# sourceMappingURL=poolPollParticipant.d.ts.map