/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PoolPollQuestionsItemOptionsItem } from './poolPollQuestionsItemOptionsItem';
export type PoolPollQuestionsItem = {
    id: string;
    prompt: string;
    options: PoolPollQuestionsItemOptionsItem[];
};
//# sourceMappingURL=poolPollQuestionsItem.d.ts.map