/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type PoolPollStatus = typeof PoolPollStatus[keyof typeof PoolPollStatus];
export declare const PoolPollStatus: {
    readonly draft: "draft";
    readonly published: "published";
};
//# sourceMappingURL=poolPollStatus.d.ts.map