/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PoolManagementInputAction } from './poolManagementInputAction';
import type { PoolManagementInputDetails } from './poolManagementInputDetails';

export interface PoolManagementInput {
  action: PoolManagementInputAction;
  /**
     * @minLength 3
     * @maxLength 1000
     */
  reason: string;
  /**
     * @minLength 8
     * @maxLength 100
     */
  requestId: string;
  details: PoolManagementInputDetails;
}
