/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PoolPollAnswers } from './poolPollAnswers';
export interface PoolPollSubmission {
    pollId: string;
    answers: PoolPollAnswers;
}
//# sourceMappingURL=poolPollSubmission.d.ts.map