/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PoolPollDraftQuestionsItemOptionsItem } from './poolPollDraftQuestionsItemOptionsItem';
export type PoolPollDraftQuestionsItem = {
    id: string;
    prompt: string;
    options: PoolPollDraftQuestionsItemOptionsItem[];
};
//# sourceMappingURL=poolPollDraftQuestionsItem.d.ts.map