/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type PoolScoringSnapshotSeason = typeof PoolScoringSnapshotSeason[keyof typeof PoolScoringSnapshotSeason];


export const PoolScoringSnapshotSeason = {
  NUMBER_20262027: 20262027,
} as const;
