/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type PublicShareView = typeof PublicShareView[keyof typeof PublicShareView];


export const PublicShareView = {
  standings: 'standings',
  analysis: 'analysis',
  roster: 'roster',
  previousDay: 'previousDay',
} as const;
