/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type PublicShareView = typeof PublicShareView[keyof typeof PublicShareView];
export declare const PublicShareView: {
    readonly standings: "standings";
    readonly analysis: "analysis";
    readonly roster: "roster";
    readonly previousDay: "previousDay";
};
//# sourceMappingURL=publicShareView.d.ts.map