/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { DailyAnalysis } from './dailyAnalysis';
import type { OwnerDetail } from './ownerDetail';
import type { OwnerStanding } from './ownerStanding';
import type { PublicShareView } from './publicShareView';

export interface PublicShare {
  view: PublicShareView;
  /** @nullable */
  date: Date | null;
  title: string;
  standings: OwnerStanding[];
  analysis: DailyAnalysis;
  roster: OwnerDetail;
}
