/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PlayerSummary } from './playerSummary';
import type { RosterAssetAssetType } from './rosterAssetAssetType';
export type RosterAsset = PlayerSummary & ({
    assetType: RosterAssetAssetType;
    /** @nullable */
    droppedAt: Date | null;
    /** @nullable */
    acquiredAt: Date | null;
    wins: number;
    shutoutWins: number;
    goalieAssists: number;
    goalieGoals: number;
});
//# sourceMappingURL=rosterAsset.d.ts.map