/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type RosterAssetAssetType = typeof RosterAssetAssetType[keyof typeof RosterAssetAssetType];
export declare const RosterAssetAssetType: {
    readonly skater: "skater";
    readonly goalieTeam: "goalieTeam";
};
//# sourceMappingURL=rosterAssetAssetType.d.ts.map