/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type ScoringRulesUpdateApplyMode = typeof ScoringRulesUpdateApplyMode[keyof typeof ScoringRulesUpdateApplyMode];
export declare const ScoringRulesUpdateApplyMode: {
    readonly historical: "historical";
};
//# sourceMappingURL=scoringRulesUpdateApplyMode.d.ts.map