/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export interface ScoringRules {
    goal: number;
    assist: number;
    powerPlayGoal: number;
    shortHandedGoal: number;
    overtimeGoal: number;
    forwardHatTrick: number;
    defensemanHatTrick: number;
    goalieTeamWin: number;
    goalieTeamShutoutWin: number;
    goalieAssist: number;
    goalieGoal: number;
    powerPlayBonusOnOvertime: boolean;
    powerPlayBonusOnHatTrick: boolean;
    revision: number;
    effectiveFrom: Date;
}
//# sourceMappingURL=scoringRules.d.ts.map