/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { ScoringRulesUpdateApplyMode } from './scoringRulesUpdateApplyMode';
/**
 * Recalculates season scoring for active players; recorded dropped-player credits and ownership cutoffs remain fixed. Forward-only rule changes are not supported.
 */
export interface ScoringRulesUpdate {
    /**
       * @minimum 0
       * @maximum 1000
       */
    goal: number;
    /**
       * @minimum 0
       * @maximum 1000
       */
    assist: number;
    /**
       * @minimum 0
       * @maximum 1000
       */
    powerPlayGoal: number;
    /**
       * @minimum 0
       * @maximum 1000
       */
    shortHandedGoal: number;
    /**
       * @minimum 0
       * @maximum 1000
       */
    overtimeGoal: number;
    /**
       * @minimum 0
       * @maximum 1000
       */
    forwardHatTrick: number;
    /**
       * @minimum 0
       * @maximum 1000
       */
    defensemanHatTrick: number;
    /**
       * @minimum 0
       * @maximum 1000
       */
    goalieTeamWin: number;
    /**
       * @minimum 0
       * @maximum 1000
       */
    goalieTeamShutoutWin: number;
    /**
       * @minimum 0
       * @maximum 1000
       */
    goalieAssist: number;
    /**
       * @minimum 0
       * @maximum 1000
       */
    goalieGoal: number;
    powerPlayBonusOnOvertime: boolean;
    powerPlayBonusOnHatTrick: boolean;
    /** @minimum 1 */
    expectedRevision: number;
    applyMode: ScoringRulesUpdateApplyMode;
}
//# sourceMappingURL=scoringRulesUpdate.d.ts.map