/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type ShareInputView = typeof ShareInputView[keyof typeof ShareInputView];
export declare const ShareInputView: {
    readonly standings: "standings";
    readonly analysis: "analysis";
    readonly roster: "roster";
    readonly previousDay: "previousDay";
};
//# sourceMappingURL=shareInputView.d.ts.map