/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export interface ShareLink {
    shareId: string;
    publicUrl: string;
}
//# sourceMappingURL=shareLink.d.ts.map