/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { PoolStanding } from './poolStanding';
import type { StandingsSnapshotStatus } from './standingsSnapshotStatus';
export interface StandingsSnapshot {
    status: StandingsSnapshotStatus;
    /** @nullable */
    reason: string | null;
    /** @nullable */
    asOf: Date | null;
    /** @nullable */
    date: Date | null;
    rows: PoolStanding[];
}
//# sourceMappingURL=standingsSnapshot.d.ts.map