/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type StandingsSnapshotStatus = typeof StandingsSnapshotStatus[keyof typeof StandingsSnapshotStatus];
export declare const StandingsSnapshotStatus: {
    readonly unavailable: "unavailable";
    readonly partial: "partial";
    readonly available: "available";
};
//# sourceMappingURL=standingsSnapshotStatus.d.ts.map