/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type TransactionPreviewGamesItem = {
  gameId: number;
  gameDate: string;
  matchup: string;
  /** @nullable */
  scheduledStart: Date | null;
  /** @nullable */
  cutoff: Date | null;
  /** @nullable */
  eligible: boolean | null;
};
