/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export interface TransactionParticipant {
  ownerId: string;
  ownerName: string;
  dropsUsed: number;
  dropsLeft: number;
  /** @nullable */
  amountOwing: number | null;
  transactionSpend: number;
}
