/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { TransactionParticipant } from './transactionParticipant';
import type { TransactionPayout } from './transactionPayout';
export interface TransactionSummary {
    baseEarnings: number;
    totalPoolEarnings: number;
    totalCompletedTransactions: number;
    transactionCost: number;
    maxDrops: number;
    payouts: TransactionPayout[];
    recordingEnabled: boolean;
    /** @nullable */
    recordingReason: string | null;
    participants: TransactionParticipant[];
}
//# sourceMappingURL=transactionSummary.d.ts.map