/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type TransactionPreviewOutgoing = {
    [key: string]: unknown;
};
//# sourceMappingURL=transactionPreviewOutgoing.d.ts.map