/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
export type TransactionPayoutPlace = typeof TransactionPayoutPlace[keyof typeof TransactionPayoutPlace];
export declare const TransactionPayoutPlace: {
    readonly NUMBER_1: 1;
    readonly NUMBER_2: 2;
    readonly NUMBER_3: 3;
};
//# sourceMappingURL=transactionPayoutPlace.d.ts.map