/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { TransactionDetails } from './transactionDetails';

export interface Transaction {
  id: string;
  ownerId: string;
  ownerName: string;
  /** @nullable */
  outgoingPlayerId: string | null;
  /** @nullable */
  outgoingPlayerName: string | null;
  /** @nullable */
  incomingPlayerId: string | null;
  /** @nullable */
  incomingPlayerName: string | null;
  effectiveAt: Date;
  createdAt: Date;
  /** @nullable */
  createdBy: string | null;
  /** @nullable */
  reversedAt: Date | null;
  paid: boolean;
  /** @nullable */
  details?: TransactionDetails;
  /** @nullable */
  transactionNumber?: number | null;
}
