/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */

export type TransactionAccessOwnersItemSkatersItem = {
  playerId: string;
  name: string;
};
