/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { TransactionAccessOwnersItemSkatersItem } from './transactionAccessOwnersItemSkatersItem';

export type TransactionAccessOwnersItem = {
  ownerId: string;
  ownerName: string;
  skaters: TransactionAccessOwnersItemSkatersItem[];
};
