/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { TransactionPayoutPlace } from './transactionPayoutPlace';
export interface TransactionPayout {
    place: TransactionPayoutPlace;
    percentage: number;
    amount: number;
    twoWayTieAmount: number;
}
//# sourceMappingURL=transactionPayout.d.ts.map