/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Hockey Pool API
 * OpenAPI spec version: 0.1.0
 */
import type { TransactionPreviewGamesItem } from './transactionPreviewGamesItem';
import type { TransactionPreviewIncoming } from './transactionPreviewIncoming';
import type { TransactionPreviewOutgoing } from './transactionPreviewOutgoing';
export interface TransactionPreview {
    ownerId: string;
    outgoing: TransactionPreviewOutgoing;
    incoming: TransactionPreviewIncoming;
    fee: number;
    dropsUsedAfter: number;
    dropsLeftAfter: number;
    serverTime: Date;
    eligibilityToken: string;
    games: TransactionPreviewGamesItem[];
    pendingVerification: boolean;
}
//# sourceMappingURL=transactionPreview.d.ts.map